from .lifecycle import (
    LIFECYCLE_VERSION,
    TransitionContext,
    TransitionError,
    allowed_transitions,
    assert_transition,
    can_transition,
    lifecycle_snapshot,
    terminal_states,
    transition_blockers,
    validate_matrices,
)
from .models import (
    Artifact,
    ArtifactStatus,
    ConfidenceVector,
    Decision,
    DecisionStatus,
    DependencyStrength,
    Engagement,
    EngagementStatus,
    EpistemicStatus,
    Evidence,
    Workstream,
    WorkstreamStatus,
)
from .ontology import (
    ONTOLOGY_VERSION,
    ArtifactType,
    Capability,
    Department,
    DepartmentDefinition,
    OntologyError,
    assert_department_owns,
    department_definition,
    has_capability,
    ontology_snapshot,
    owning_department,
    resolve_artifact_type,
    resolve_department,
)
from .registry import (
    MAIN_BRANCH,
    MERGE_MATRIX,
    REGISTRY_VERSION,
    ArtifactRegistry,
    ArtifactVersion,
    MergeError,
    MergeOutcome,
    MergeResolution,
    content_fingerprint,
    validate_merge_matrix,
)
from .roles import (
    ROLE_CONTRACT_VERSION,
    ROLE_REGISTRY,
    RoleContract,
    RoleContractError,
    assert_evidence_sufficient,
    assert_role_may_produce,
    get_role,
    role_snapshot,
    roles_for_department,
    validate_registry,
)

__all__ = [
    # models
    "Artifact",
    "ArtifactStatus",
    "ConfidenceVector",
    "Decision",
    "DecisionStatus",
    "DependencyStrength",
    "Engagement",
    "EngagementStatus",
    "EpistemicStatus",
    "Evidence",
    "Workstream",
    "WorkstreamStatus",
    # N1 ontology
    "ONTOLOGY_VERSION",
    "ArtifactType",
    "Capability",
    "Department",
    "DepartmentDefinition",
    "OntologyError",
    "assert_department_owns",
    "department_definition",
    "has_capability",
    "ontology_snapshot",
    "owning_department",
    "resolve_artifact_type",
    "resolve_department",
    # N2 lifecycle
    "LIFECYCLE_VERSION",
    "TransitionContext",
    "TransitionError",
    "allowed_transitions",
    "assert_transition",
    "can_transition",
    "lifecycle_snapshot",
    "terminal_states",
    "transition_blockers",
    "validate_matrices",
    # N3 roles
    "ROLE_CONTRACT_VERSION",
    "ROLE_REGISTRY",
    "RoleContract",
    "RoleContractError",
    "assert_evidence_sufficient",
    "assert_role_may_produce",
    "get_role",
    "role_snapshot",
    "roles_for_department",
    "validate_registry",
    # N4 registry
    "MAIN_BRANCH",
    "MERGE_MATRIX",
    "REGISTRY_VERSION",
    "ArtifactRegistry",
    "ArtifactVersion",
    "MergeError",
    "MergeOutcome",
    "MergeResolution",
    "content_fingerprint",
    "validate_merge_matrix",
]
