#!/usr/bin/env python3
"""Compile the ABC-v6 manifests from code, so they cannot drift from what runs.

    python scripts/compile_abc_manifests.py --write   # regenerate runtime/abc/*.yaml
    python scripts/compile_abc_manifests.py --check   # exit 1 if any file differs from code

Each file is JSON, which is valid YAML 1.2, after one ``#`` header line. The
content is deterministic: no timestamps, no probe results, no environment.
Environment-dependent facts (capability probes, command results) belong in
``runtime/abc/verification-seal.json``, written by ``scripts/seal_abc_build.py``.
"""

from __future__ import annotations

import argparse
import importlib
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

OUT = ROOT / "runtime" / "abc"
HEADER = "# Generated by scripts/compile_abc_manifests.py from code. Do not edit; run --write.\n"
TESTS = "services/langgraph/tests/test_abc_v6.py"

INVARIANTS = (
    ("I01", "Real execution default; simulation explicitly selected and permanently labeled.",
     ["services.langgraph.agency.intake.release:artifact_release_verdict",
      "services.langgraph.agency.intake.contracts:ExecutionMode"],
     [f"{TESTS}::test_t05_simulation_cannot_release"]),
    ("I02", "Missing capability -> BLOCKED; never substitute generated descriptions.",
     ["services.langgraph.agency.visual.router:route", "services.langgraph.agency.visual.capabilities:probe_all"],
     [f"{TESTS}::test_t06_missing_provider_is_a_truthful_blocker"]),
    ("I03", "No unauthorized publish, deploy, send, spend, purchase or production mutation.",
     ["services.langgraph.agency.durable.governance:decide",
      "services.langgraph.integrations.paid_media:spend_execution_available"],
     [f"{TESTS}::test_t15_publish_spend_send_never_dispatched"]),
    ("I04", "Every completion claim requires persisted bytes and independent observation.",
     ["services.langgraph.agency.visual.engine:readback_verify", "services.langgraph.agency.durable.ticks:run_tick"],
     [f"{TESTS}::test_t13_corrupt_or_stale_bytes_invalidate_verification"]),
    ("I05", "Approval binds exact artifact hash, version, scope and authorized reviewer.",
     ["services.langgraph.agency.intake.release:open_artifact_approval",
      "services.langgraph.agency.intake.release:artifact_release_verdict"],
     [f"{TESTS}::test_t14_modified_artifact_invalidates_old_approval"]),
    ("I06", "Tenant/project isolation across memory, execution, artifacts and telemetry.",
     ["services.langgraph.agency.durable.visual_job:submit_visual_job",
      "services.langgraph.agency.durable.visual_job:VisualRenderHandler"],
     [f"{TESTS}::test_t04_cross_tenant_and_cross_project_blocked"]),
    ("I07", "Recurring work uses durable state, bounded ticks and stable idempotency.",
     ["services.langgraph.persistence.durable_runs:claim_due_job",
      "services.langgraph.persistence.durable_runs:reserve_intent",
      "services.langgraph.agency.durable.ticks:idempotency_key"],
     [f"{TESTS}::test_t03_duplicate_ticks_do_not_duplicate_effects", f"{TESTS}::test_t16_crash_recovery_adopts_persisted_effect"]),
    ("I08", "Preserve existing orchestration, storage, governance and event semantics.",
     ["services.langgraph.agency.delivery.workflow:topology",
      "services.langgraph.persistence.projects:revise_project_artifact"],
     [f"{TESTS}::test_t19_domain_stages_preserved"]),
    ("I09", "Verify external interfaces against installed versions and official sources.",
     ["services.langgraph.agency.visual.capabilities:probe_blender",
      "services.langgraph.agency.visual.capabilities:probe_video"],
     [f"{TESTS}::test_t06_missing_provider_is_a_truthful_blocker"]),
    ("I10", "Never represent subjective AI assessment as objective technical proof.",
     ["services.langgraph.agency.visual.verify:HUMAN_LEVELS"],
     [f"{TESTS}::test_q5_to_q7_are_never_machine_passed"]),
    ("I11", "Never weaken content safety, rights checks or security to improve throughput.",
     ["services.langgraph.agency.visual.router:route", "services.langgraph.agency.execution_fabric.verifiers:svg_safety"],
     [f"{TESTS}::test_t17_unknown_rights_block_production"]),
    ("I12", "All code changes remain reviewable, reversible where feasible and testable.",
     ["services.langgraph.agency.durable.build_dag:BUILD_DAG"],
     [f"{TESTS}::test_t20_seal_never_counts_not_run_as_passed"]),
)


def _resolve(ref: str) -> bool:
    module, _, attr = ref.partition(":")
    try:
        return hasattr(importlib.import_module(module), attr)
    except ImportError:
        return False


def system_genome() -> dict:
    from services.langgraph.agency.delivery.workflow import CONTRACT_WORKFLOW, LEGACY_WORKFLOW, topology
    from services.langgraph.agency.durable.build_dag import BUILD_DAG_VERSION
    from services.langgraph.agency.durable.fsm import RUN_FSM_VERSION
    from services.langgraph.agency.durable.genome import GENOME_SCHEMA_VERSION, VERIFIER_REGISTRY
    from services.langgraph.agency.durable.governance import GOVERNANCE_VERSION
    from services.langgraph.agency.visual.capabilities import PROBES
    from services.langgraph.agency.visual.contracts import VISUAL_ENGINE_VERSION

    invariants = []
    for iid, text, symbols, tests in INVARIANTS:
        missing = [s for s in symbols if not _resolve(s)]
        if missing:
            raise SystemExit(f"{iid}: enforcing symbol(s) not found: {missing}")
        invariants.append({"id": iid, "statement": text, "enforced_by": symbols, "tests": tests})
    return {
        "schema_version": "amc-system-genome/v1",
        "domain_stages": {LEGACY_WORKFLOW: topology(LEGACY_WORKFLOW)["node_ids"],
                          CONTRACT_WORKFLOW: topology(CONTRACT_WORKFLOW)["node_ids"]},
        "schema_versions": {"mission_genome": GENOME_SCHEMA_VERSION, "build_dag": BUILD_DAG_VERSION,
                            "run_fsm": RUN_FSM_VERSION, "governance": GOVERNANCE_VERSION,
                            "visual_engine": VISUAL_ENGINE_VERSION},
        "invariants": invariants,
        "visual_routes": {route.value: f"{probe.__module__}:{probe.__name__}" for route, probe in PROBES.items()},
        "verifier_registry": VERIFIER_REGISTRY,
        "predicates": {
            "BuildComplete": "RequiredArtifactsExist AND HashesMatch AND BuildChecksPass AND NoCriticalUnresolvedDependencies",
            "ReleaseEligible": "BuildComplete AND IndependentReviewPassed AND AuthorizationValid AND ApprovalCurrent "
                               "AND NoSimulationContamination",
            "RuntimeActive": "SchedulerConfigured AND WorkerOperational AND DurableStateAvailable AND ActivationAuthorized",
            "note": "Three separate predicates; none implies another.",
        },
        "hosted_generation_apis": "NONE: production inference and rendering are local",
    }


def run_fsm() -> dict:
    from services.langgraph.agency.durable.fsm import BLOCKED, CLAIMABLE, IN_FLIGHT, RUN_FSM_VERSION, TERMINAL, TRANSITIONS
    from services.langgraph.agency.durable.ticks import MAX_RETRIES, RETRY_BACKOFF_S, TICK_VERSION

    return {
        "schema_version": RUN_FSM_VERSION, "tick_version": TICK_VERSION,
        "states": [s.value for s in TRANSITIONS],
        "transitions": {s.value: sorted(t.value for t in dst) for s, dst in TRANSITIONS.items()},
        "sets": {"in_flight": sorted(s.value for s in IN_FLIGHT), "claimable": sorted(s.value for s in CLAIMABLE),
                 "terminal": sorted(s.value for s in TERMINAL), "blocked": sorted(s.value for s in BLOCKED)},
        "tick_steps": ["acquire lease + fencing token (CAS on version)", "precheck authority, budget, capability",
                       "load job spec (server-written principal snapshot)", "compute idempotency key",
                       "persist write intent with pre-image", "dispatch authorized local capability",
                       "read back persisted artifact", "independent verifier", "fenced commit of receipt + state",
                       "record tick telemetry and next_due_at", "release lease; process invocation ends"],
        "idempotency_key": "SHA256(canonical(tenant, project, job, logical_tick, operation, target, input_hash, contract_version))",
        "retry": {"max_retries": MAX_RETRIES, "backoff_s": list(RETRY_BACKOFF_S),
                  "RETRY_SAFE": "bounded retry", "COMPENSATABLE": "not used by any registered handler",
                  "NON_RETRYABLE": "reconcile or DEAD_LETTER for a human"},
        "guarantee": "at-least-once local dispatch with intent deduplication and pre-image reconciliation; "
                     "not exactly-once, and no external effects are dispatched",
        "operation": "ticks are invoked explicitly; no persistent worker or scheduler is deployed by this change",
    }


def build_dag() -> dict:
    from services.langgraph.agency.durable.build_dag import as_document

    return as_document()


def governance() -> dict:
    from services.langgraph.agency.durable.governance import as_document

    return as_document()


FILES = {"SYSTEM_GENOME.yaml": system_genome, "build-dag.yaml": build_dag, "run-fsm.yaml": run_fsm,
         "governance-matrix.yaml": governance}


def render(builder) -> str:
    return HEADER + json.dumps(builder(), indent=2, sort_keys=True) + "\n"


def load(path: Path) -> dict:
    return json.loads("".join(line for line in path.read_text().splitlines(keepends=True) if not line.startswith("#")))


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true")
    mode.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)
    drift = []
    for name, builder in FILES.items():
        text, path = render(builder), OUT / name
        if args.write:
            OUT.mkdir(parents=True, exist_ok=True)
            path.write_text(text)
        elif not path.is_file() or path.read_text() != text:
            drift.append(name)
    if drift:
        print(f"ABC manifests out of date: {drift}; run scripts/compile_abc_manifests.py --write", file=sys.stderr)
        return 1
    print("ABC manifests " + ("written" if args.write else "match code") + f": {sorted(FILES)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
