import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { describe, expect, it } from 'vitest';
import { DesignBriefSchema, UIUXDesignIRSchema, UIUXTerminalSchema } from '../src';

// Generated by the real Python compiler; services/langgraph/tests/test_ui_ux.py
// fails if the compiler output drifts from this file, so a pass here proves the
// Zod twin accepts exactly what the backend emits.
const fixture = JSON.parse(readFileSync(join(__dirname, 'fixtures', 'uiux-design-ir.json'), 'utf-8'));

describe('UIUXDesignIRSchema parity with the Python compiler', () => {
  it('parses the backend-generated IR fixture', () => {
    const parsed = UIUXDesignIRSchema.parse(fixture);
    expect(parsed.schema_version).toBe('amc-uiux-ir/v1');
    expect(parsed.handoff_only).toBe(true);
    expect(parsed.tokens.format).toBe('DTCG 2025.10');
  });

  it('is strict like Pydantic extra="forbid"', () => {
    expect(UIUXDesignIRSchema.safeParse({ ...fixture, unexpected: true }).success).toBe(false);
    const screen = { ...fixture.screens[0], trace: { ...fixture.screens[0].trace, extra: 'x' } };
    expect(UIUXDesignIRSchema.safeParse({ ...fixture, screens: [screen] }).success).toBe(false);
  });

  it('has no generated/deployed terminal state', () => {
    for (const forbidden of ['UI_GENERATED', 'ASSET_GENERATED', 'DEPLOYED']) {
      expect(UIUXTerminalSchema.safeParse(forbidden).success).toBe(false);
    }
  });

  it('rejects a MEASURED metric without a timestamp', () => {
    const budgets = [{ ...fixture.performance.budgets[0], truth: 'MEASURED', timestamp: null }];
    const bad = { ...fixture, performance: { ...fixture.performance, budgets } };
    expect(UIUXDesignIRSchema.safeParse(bad).success).toBe(false);
  });

  it('keeps DesignBrief backward compatible (ui_ux optional)', () => {
    const base = { palette: ['#000000'], typography_direction: 't', imagery_style: 'i', layout_notes: 'l' };
    expect(DesignBriefSchema.parse(base).ui_ux).toBeUndefined();
    expect(DesignBriefSchema.parse({ ...base, ui_ux: null }).ui_ux).toBeNull();
    expect(DesignBriefSchema.parse({ ...base, ui_ux: fixture }).ui_ux?.spec_hash).toBe(fixture.spec_hash);
  });
});
