create schema if not exists amc;
revoke all on schema amc from anon, authenticated;

create table if not exists amc.tenants (tenant_id text primary key, name text not null, created_at timestamptz not null default now());
create table if not exists amc.projects (project_id text primary key, tenant_id text not null references amc.tenants(tenant_id) on delete cascade, name text not null, created_at timestamptz not null default now());
create index if not exists idx_amc_projects_tenant on amc.projects(tenant_id);
create table if not exists amc.tenant_memberships (tenant_id text not null references amc.tenants(tenant_id) on delete cascade, user_id uuid not null references auth.users(id) on delete cascade, role text not null default 'operator', allowed_project_ids text[] not null default '{}', active boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), primary key (tenant_id, user_id));
create index if not exists idx_amc_memberships_user on amc.tenant_memberships(user_id) where active;
create table if not exists amc.runs (run_id text primary key, tenant_id text not null, project_id text not null references amc.projects(project_id) on delete restrict, pipeline text not null, status text not null, metadata jsonb not null default '{}'::jsonb, result jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create index if not exists idx_amc_runs_tenant_project on amc.runs(tenant_id, project_id, created_at desc);
create index if not exists idx_amc_runs_status on amc.runs(status, updated_at desc);
create table if not exists amc.approvals (approval_id text primary key, run_id text not null references amc.runs(run_id) on delete cascade, tenant_id text not null, project_id text not null, reason text not null, confidence double precision, status text not null default 'pending' check (status in ('pending','resolved')), reviewer text, decision text check (decision is null or decision in ('approve','reject')), created_at timestamptz not null default now(), decided_at timestamptz);
create index if not exists idx_amc_approvals_tenant_status on amc.approvals(tenant_id, status, created_at);
create table if not exists amc.idempotency_records (scope text not null, key text not null, request_hash text not null, status text not null check (status in ('executing','completed','failed')), result jsonb, error text, attempt_count integer not null default 1 check (attempt_count > 0), created_at timestamptz not null, updated_at timestamptz not null, expires_at timestamptz not null, primary key (scope, key));
create index if not exists idx_amc_idempotency_expires on amc.idempotency_records(expires_at);
create table if not exists amc.run_event_counters (run_id text primary key references amc.runs(run_id) on delete cascade, next_sequence bigint not null default 0 check (next_sequence >= 0));
create table if not exists amc.run_events (event_id text primary key, run_id text not null references amc.runs(run_id) on delete cascade, tenant_id text not null, project_id text not null, sequence bigint not null, schema_version text not null, event_type text not null, node_id text, observed_at timestamptz not null, started_at timestamptz, completed_at timestamptz, persisted_at timestamptz not null, checkpoint_ref text, safe_payload jsonb not null default '{}'::jsonb, redactions_applied jsonb not null default '[]'::jsonb, unique (run_id, sequence));
create index if not exists idx_amc_events_cursor on amc.run_events(run_id, sequence);
create table if not exists amc.analytics_events (event_id uuid primary key default gen_random_uuid(), tenant_id text not null, project_id text not null, run_id text references amc.runs(run_id) on delete set null, event_name text not null, source text not null default 'amc_first_party', occurred_at timestamptz not null default now(), properties jsonb not null default '{}'::jsonb, schema_version text not null default 'analytics-event-v1');
create index if not exists idx_amc_analytics_tenant_time on amc.analytics_events(tenant_id, project_id, occurred_at desc);
create table if not exists amc.publication_jobs (job_id uuid primary key default gen_random_uuid(), run_id text not null references amc.runs(run_id) on delete cascade, tenant_id text not null, project_id text not null, provider text not null, mode text not null default 'dry_run' check (mode in ('dry_run','live')), status text not null default 'pending' check (status in ('pending','validated','executing','completed','failed','blocked')), idempotency_key text not null, payload jsonb not null, external_id text, error text, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique (provider, idempotency_key));
create table if not exists amc.spend_authorizations (authorization_id uuid primary key default gen_random_uuid(), run_id text references amc.runs(run_id) on delete set null, tenant_id text not null, project_id text not null, provider text not null, amount_minor bigint not null check (amount_minor >= 0), currency text not null check (char_length(currency) = 3), status text not null default 'pending' check (status in ('pending','approved','rejected','executed','cancelled')), requested_by text not null, approved_by text, reason text not null, external_id text, created_at timestamptz not null default now(), decided_at timestamptz, executed_at timestamptz);
create index if not exists idx_amc_spend_tenant_status on amc.spend_authorizations(tenant_id, status, created_at desc);

comment on schema amc is 'Agent Mission Control production persistence. Not exposed to anon/authenticated Data API roles.';
